const STUDENT = {
  name: 'Agostinho Mafuco César Cambriz',
  details: [
    { id: 0, detailType: 'Nº', content: '11967' },
    { id: 1, detailType: 'Classe: ', content: '12ª' },
    { id: 2, detailType: 'Curso: ', content: 'Enfermagem' },
    { id: 3, detailType: 'Turno: ', content: 'Manhã' },
  ],
  grades: {
    THEAD: [
      { id: 0, content: 'Disciplinas', visible: true, colSpan: 0 },
      { id: 1, content: 'Iº Trimestre', visible: true, colSpan: 5 },
      { id: 2, content: 'IIº Trimestre', visible: true, colSpan: 5 },
      { id: 3, content: 'IIIº Trimestre', visible: true, colSpan: 6 },
    ],
    TEST_TYPES: [
      { id: 0, testType: '0', visible: false },
      { id: 1, testType: 'P1', visible: true },
      { id: 2, testType: 'P2', visible: true },
      { id: 3, testType: 'PT', visible: true },
      { id: 4, testType: 'MT1', visible: true },
      { id: 5, testType: '0', visible: false },
      { id: 6, testType: 'P1', visible: true },
      { id: 7, testType: 'P2', visible: true },
      { id: 8, testType: 'PT', visible: true },
      { id: 9, testType: 'MT2', visible: true },
      { id: 10, testType: '0', visible: false },
      { id: 11, testType: 'P1', visible: true },
      { id: 12, testType: 'P2', visible: true },
      { id: 13, testType: 'PT', visible: true },
      { id: 14, testType: 'NEE', visible: true },
      { id: 15, testType: 'MF', visible: true },
      { id: 16, testType: 'MFD', visible: true },
    ],
    TBODY: [
      {
        id: 0,
        values: [
          { id: 0, value: 'Língua portuguesa', visible: true },
          { id: 1, value: 10, visible: true },
          { id: 2, value: 8, visible: true },
          { id: 3, value: 12, visible: true },
          { id: 4, value: 13, visible: true },
          { id: 5, value: 8, visible: false },
          { id: 6, value: 12, visible: true },
          { id: 7, value: 15, visible: true },
          { id: 8, value: 13, visible: true },
          { id: 9, value: 7, visible: true },
          { id: 10, value: 9, visible: false },
          { id: 11, value: 6, visible: true },
          { id: 12, value: 17, visible: true },
          { id: 13, value: 2, visible: true },
          { id: 14, value: 3, visible: true },
          { id: 15, value: 19, visible: true },
          { id: 16, value: 20, visible: true },
        ],
      },
      {
        id: 1,
        values: [
          { id: 0, value: 'Biologia', visible: true },
          { id: 1, value: 8, visible: true },
          { id: 2, value: 9, visible: true },
          { id: 3, value: 10, visible: true },
          { id: 4, value: 19, visible: true },
          { id: 5, value: 12, visible: false },
          { id: 6, value: 5, visible: true },
          { id: 7, value: 2, visible: true },
          { id: 8, value: 1, visible: true },
          { id: 9, value: 20, visible: true },
          { id: 10, value: 10, visible: false },
          { id: 11, value: 17, visible: true },
          { id: 12, value: 9, visible: true },
          { id: 13, value: 2, visible: true },
          { id: 14, value: 12, visible: true },
          { id: 15, value: 0, visible: true },
          { id: 16, value: 1, visible: true },
        ],
      },
      {
        id: 2,
        values: [
          { id: 0, value: 'Saúde da criança', visible: true },
          { id: 1, value: 10, visible: true },
          { id: 2, value: 8, visible: true },
          { id: 3, value: 12, visible: true },
          { id: 4, value: 13, visible: true },
          { id: 5, value: 8, visible: false },
          { id: 6, value: 12, visible: true },
          { id: 7, value: 15, visible: true },
          { id: 8, value: 13, visible: true },
          { id: 9, value: 7, visible: true },
          { id: 10, value: 9, visible: false },
          { id: 11, value: 6, visible: true },
          { id: 12, value: 17, visible: true },
          { id: 13, value: 2, visible: true },
          { id: 14, value: 3, visible: true },
          { id: 15, value: 19, visible: true },
          { id: 16, value: 20, visible: true },
        ],
      },
      {
        id: 3,
        values: [
          { id: 0, value: 'Matemática Discreta', visible: true },
          { id: 1, value: 8, visible: true },
          { id: 2, value: 9, visible: true },
          { id: 3, value: 10, visible: true },
          { id: 4, value: 19, visible: true },
          { id: 5, value: 12, visible: false },
          { id: 6, value: 5, visible: true },
          { id: 7, value: 2, visible: true },
          { id: 8, value: 1, visible: true },
          { id: 9, value: 20, visible: true },
          { id: 10, value: 10, visible: false },
          { id: 11, value: 17, visible: true },
          { id: 12, value: 9, visible: true },
          { id: 13, value: 2, visible: true },
          { id: 14, value: 12, visible: true },
          { id: 15, value: 0, visible: true },
          { id: 16, value: 1, visible: true },
        ],
      },
      {
        id: 4,
        values: [
          { id: 0, value: 'Gestão de redes', visible: true },
          { id: 1, value: 10, visible: true },
          { id: 2, value: 8, visible: true },
          { id: 3, value: 12, visible: true },
          { id: 4, value: 13, visible: true },
          { id: 5, value: 8, visible: false },
          { id: 6, value: 12, visible: true },
          { id: 7, value: 15, visible: true },
          { id: 8, value: 13, visible: true },
          { id: 9, value: 7, visible: true },
          { id: 10, value: 9, visible: false },
          { id: 11, value: 6, visible: true },
          { id: 12, value: 17, visible: true },
          { id: 13, value: 2, visible: true },
          { id: 14, value: 3, visible: true },
          { id: 15, value: 19, visible: true },
          { id: 16, value: 20, visible: true },
        ],
      },
      {
        id: 5,
        values: [
          { id: 0, value: 'Química', visible: true },
          { id: 1, value: 8, visible: true },
          { id: 2, value: 9, visible: true },
          { id: 3, value: 10, visible: true },
          { id: 4, value: 19, visible: true },
          { id: 5, value: 12, visible: false },
          { id: 6, value: 5, visible: true },
          { id: 7, value: 2, visible: true },
          { id: 8, value: 1, visible: true },
          { id: 9, value: 20, visible: true },
          { id: 10, value: 10, visible: false },
          { id: 11, value: 17, visible: true },
          { id: 12, value: 9, visible: true },
          { id: 13, value: 2, visible: true },
          { id: 14, value: 12, visible: true },
          { id: 15, value: 0, visible: true },
          { id: 16, value: 1, visible: true },
        ],
      },
      {
        id: 6,
        values: [
          { id: 0, value: 'Educação Física', visible: true },
          { id: 1, value: 10, visible: true },
          { id: 2, value: 8, visible: true },
          { id: 3, value: 12, visible: true },
          { id: 4, value: 13, visible: true },
          { id: 5, value: 8, visible: false },
          { id: 6, value: 12, visible: true },
          { id: 7, value: 15, visible: true },
          { id: 8, value: 13, visible: true },
          { id: 9, value: 7, visible: true },
          { id: 10, value: 9, visible: false },
          { id: 11, value: 6, visible: true },
          { id: 12, value: 17, visible: true },
          { id: 13, value: 2, visible: true },
          { id: 14, value: 3, visible: true },
          { id: 15, value: 19, visible: true },
          { id: 16, value: 20, visible: true },
        ],
      },
      {
        id: 7,
        values: [
          { id: 0, value: 'Estatística', visible: true },
          { id: 1, value: 8, visible: true },
          { id: 2, value: 9, visible: true },
          { id: 3, value: 10, visible: true },
          { id: 4, value: 19, visible: true },
          { id: 5, value: 12, visible: false },
          { id: 6, value: 5, visible: true },
          { id: 7, value: 2, visible: true },
          { id: 8, value: 1, visible: true },
          { id: 9, value: 20, visible: true },
          { id: 10, value: 10, visible: false },
          { id: 11, value: 17, visible: true },
          { id: 12, value: 9, visible: true },
          { id: 13, value: 2, visible: true },
          { id: 14, value: 12, visible: true },
          { id: 15, value: 0, visible: true },
          { id: 16, value: 1, visible: true },
        ],
      },
      {
        id: 8,
        values: [
          { id: 0, value: 'Inglês', visible: true },
          { id: 1, value: 10, visible: true },
          { id: 2, value: 8, visible: true },
          { id: 3, value: 12, visible: true },
          { id: 4, value: 13, visible: true },
          { id: 5, value: 8, visible: false },
          { id: 6, value: 12, visible: true },
          { id: 7, value: 15, visible: true },
          { id: 8, value: 13, visible: true },
          { id: 9, value: 7, visible: true },
          { id: 10, value: 9, visible: false },
          { id: 11, value: 6, visible: true },
          { id: 12, value: 17, visible: true },
          { id: 13, value: 2, visible: true },
          { id: 14, value: 3, visible: true },
          { id: 15, value: 19, visible: true },
          { id: 16, value: 20, visible: true },
        ],
      },
      {
        id: 9,
        values: [
          { id: 0, value: 'Comportamento Organizacional', visible: true },
          { id: 1, value: 8, visible: true },
          { id: 2, value: 9, visible: true },
          { id: 3, value: 10, visible: true },
          { id: 4, value: 19, visible: true },
          { id: 5, value: 12, visible: false },
          { id: 6, value: 5, visible: true },
          { id: 7, value: 2, visible: true },
          { id: 8, value: 1, visible: true },
          { id: 9, value: 20, visible: true },
          { id: 10, value: 10, visible: false },
          { id: 11, value: 17, visible: true },
          { id: 12, value: 9, visible: true },
          { id: 13, value: 2, visible: true },
          { id: 14, value: 12, visible: true },
          { id: 15, value: 0, visible: true },
          { id: 16, value: 1, visible: true },
        ],
      },
    ],
  },
}

export { STUDENT }
