const STUDENT = {
  name: 'Agostinho Mafuco César Cambriz',
  details: [
    { id: 0, detailType: 'Nº', content: '11967' },
    { id: 1, detailType: 'Classe: ', content: '12ª' },
    { id: 2, detailType: 'Curso: ', content: 'Enfermagem' },
    { id: 3, detailType: 'Turno: ', content: 'Manhã' },
  ],
  grades: {
    THEAD: [
      { id: 0, content: 'Disciplinas', visible: true, colSpan: 0 },
      { id: 1, content: 'Iº Trimestre', visible: true, colSpan: 5 },
      { id: 2, content: 'IIº Trimestre', visible: true, colSpan: 5 },
      { id: 3, content: 'IIIº Trimestre', visible: true, colSpan: 6 },
    ],
    TEST_TYPES: [
      { id: 0, testType: '0', visible: false },
      { id: 1, testType: 'P1', visible: true },
      { id: 2, testType: 'P2', visible: true },
      { id: 3, testType: 'PT', visible: true },
      { id: 4, testType: 'MT1', visible: true },
      { id: 5, testType: '0', visible: false },
      { id: 6, testType: 'P1', visible: true },
      { id: 7, testType: 'P2', visible: true },
      { id: 8, testType: 'PT', visible: true },
      { id: 9, testType: 'MT2', visible: true },
      { id: 10, testType: '0', visible: false },
      { id: 11, testType: 'P1', visible: true },
      { id: 12, testType: 'P2', visible: true },
      { id: 13, testType: 'PT', visible: true },
      { id: 14, testType: 'NEE', visible: true },
      { id: 15, testType: 'MF', visible: true },
      { id: 16, testType: 'MFD', visible: true },
    ],
    TBODY: [
      {
        id: 0,
        subject: 'Língua portuguesa',
        notes: [
          { id: 1, note: 10, visible: true },
          { id: 2, note: 8, visible: true },
          { id: 3, note: 12, visible: true },
          { id: 4, note: 13, visible: true },
          { id: 5, note: 8, visible: false },
          { id: 6, note: 12, visible: true },
          { id: 7, note: 15, visible: true },
          { id: 8, note: 13, visible: true },
          { id: 9, note: 7, visible: true },
          { id: 10, note: 9, visible: false },
          { id: 11, note: 6, visible: true },
          { id: 12, note: 17, visible: true },
          { id: 13, note: 2, visible: true },
          { id: 14, note: 3, visible: true },
          { id: 15, note: 19, visible: true },
          { id: 16, note: 20, visible: true },
        ],
      },
      {
        id: 1,
        subject: 'Biologia',
        notes: [
          { id: 1, note: 8, visible: true },
          { id: 2, note: 9, visible: true },
          { id: 3, note: 10, visible: true },
          { id: 4, note: 19, visible: true },
          { id: 5, note: 12, visible: false },
          { id: 6, note: 5, visible: true },
          { id: 7, note: 2, visible: true },
          { id: 8, note: 1, visible: true },
          { id: 9, note: 20, visible: true },
          { id: 10, note: 10, visible: false },
          { id: 11, note: 17, visible: true },
          { id: 12, note: 9, visible: true },
          { id: 13, note: 2, visible: true },
          { id: 14, note: 12, visible: true },
          { id: 15, note: 0, visible: true },
          { id: 16, note: 1, visible: true },
        ],
      },
      {
        id: 2,
        subject: 'Saúde da criança',
        notes: [
          { id: 1, note: 10, visible: true },
          { id: 2, note: 8, visible: true },
          { id: 3, note: 12, visible: true },
          { id: 4, note: 13, visible: true },
          { id: 5, note: 8, visible: false },
          { id: 6, note: 12, visible: true },
          { id: 7, note: 15, visible: true },
          { id: 8, note: 13, visible: true },
          { id: 9, note: 7, visible: true },
          { id: 10, note: 9, visible: false },
          { id: 11, note: 6, visible: true },
          { id: 12, note: 17, visible: true },
          { id: 13, note: 2, visible: true },
          { id: 14, note: 3, visible: true },
          { id: 15, note: 19, visible: true },
          { id: 16, note: 20, visible: true },
        ],
      },
      {
        id: 3,
        subject: 'Matemática Discreta',
        notes: [
          { id: 1, note: 8, visible: true },
          { id: 2, note: 9, visible: true },
          { id: 3, note: 10, visible: true },
          { id: 4, note: 19, visible: true },
          { id: 5, note: 12, visible: false },
          { id: 6, note: 5, visible: true },
          { id: 7, note: 2, visible: true },
          { id: 8, note: 1, visible: true },
          { id: 9, note: 20, visible: true },
          { id: 10, note: 10, visible: false },
          { id: 11, note: 17, visible: true },
          { id: 12, note: 9, visible: true },
          { id: 13, note: 2, visible: true },
          { id: 14, note: 12, visible: true },
          { id: 15, note: 0, visible: true },
          { id: 16, note: 1, visible: true },
        ],
      },
      {
        id: 4,
        subject: 'Gestão de redes',
        notes: [
          { id: 1, note: 10, visible: true },
          { id: 2, note: 8, visible: true },
          { id: 3, note: 12, visible: true },
          { id: 4, note: 13, visible: true },
          { id: 5, note: 8, visible: false },
          { id: 6, note: 12, visible: true },
          { id: 7, note: 15, visible: true },
          { id: 8, note: 13, visible: true },
          { id: 9, note: 7, visible: true },
          { id: 10, note: 9, visible: false },
          { id: 11, note: 6, visible: true },
          { id: 12, note: 17, visible: true },
          { id: 13, note: 2, visible: true },
          { id: 14, note: 3, visible: true },
          { id: 15, note: 19, visible: true },
          { id: 16, note: 20, visible: true },
        ],
      },
      {
        id: 5,
        subject: 'Química',
        notes: [
          { id: 1, note: 8, visible: true },
          { id: 2, note: 9, visible: true },
          { id: 3, note: 10, visible: true },
          { id: 4, note: 19, visible: true },
          { id: 5, note: 12, visible: false },
          { id: 6, note: 5, visible: true },
          { id: 7, note: 2, visible: true },
          { id: 8, note: 1, visible: true },
          { id: 9, note: 20, visible: true },
          { id: 10, note: 10, visible: false },
          { id: 11, note: 17, visible: true },
          { id: 12, note: 9, visible: true },
          { id: 13, note: 2, visible: true },
          { id: 14, note: 12, visible: true },
          { id: 15, note: 0, visible: true },
          { id: 16, note: 1, visible: true },
        ],
      },
      {
        id: 6,
        subject: 'Educação Física',
        notes: [
          { id: 1, note: 10, visible: true },
          { id: 2, note: 8, visible: true },
          { id: 3, note: 12, visible: true },
          { id: 4, note: 13, visible: true },
          { id: 5, note: 8, visible: false },
          { id: 6, note: 12, visible: true },
          { id: 7, note: 15, visible: true },
          { id: 8, note: 13, visible: true },
          { id: 9, note: 7, visible: true },
          { id: 10, note: 9, visible: false },
          { id: 11, note: 6, visible: true },
          { id: 12, note: 17, visible: true },
          { id: 13, note: 2, visible: true },
          { id: 14, note: 3, visible: true },
          { id: 15, note: 19, visible: true },
          { id: 16, note: 20, visible: true },
        ],
      },
      {
        id: 7,
        subject: 'Estatística',
        notes: [
          { id: 1, note: 8, visible: true },
          { id: 2, note: 9, visible: true },
          { id: 3, note: 10, visible: true },
          { id: 4, note: 19, visible: true },
          { id: 5, note: 12, visible: false },
          { id: 6, note: 5, visible: true },
          { id: 7, note: 2, visible: true },
          { id: 8, note: 1, visible: true },
          { id: 9, note: 20, visible: true },
          { id: 10, note: 10, visible: false },
          { id: 11, note: 17, visible: true },
          { id: 12, note: 9, visible: true },
          { id: 13, note: 2, visible: true },
          { id: 14, note: 12, visible: true },
          { id: 15, note: 0, visible: true },
          { id: 16, note: 1, visible: true },
        ],
      },
      {
        id: 8,
        subject: 'Inglês',
        notes: [
          { id: 1, note: 10, visible: true },
          { id: 2, note: 8, visible: true },
          { id: 3, note: 12, visible: true },
          { id: 4, note: 13, visible: true },
          { id: 5, note: 8, visible: false },
          { id: 6, note: 12, visible: true },
          { id: 7, note: 15, visible: true },
          { id: 8, note: 13, visible: true },
          { id: 9, note: 7, visible: true },
          { id: 10, note: 9, visible: false },
          { id: 11, note: 6, visible: true },
          { id: 12, note: 17, visible: true },
          { id: 13, note: 2, visible: true },
          { id: 14, note: 3, visible: true },
          { id: 15, note: 19, visible: true },
          { id: 16, note: 20, visible: true },
        ],
      },
      {
        id: 9,
        subject: 'Comportamento Organizacional',
        notes: [
          { id: 1, note: 8, visible: true },
          { id: 2, note: 9, visible: true },
          { id: 3, note: 10, visible: true },
          { id: 4, note: 19, visible: true },
          { id: 5, note: 12, visible: false },
          { id: 6, note: 5, visible: true },
          { id: 7, note: 2, visible: true },
          { id: 8, note: 1, visible: true },
          { id: 9, note: 20, visible: true },
          { id: 10, note: 10, visible: false },
          { id: 11, note: 17, visible: true },
          { id: 12, note: 9, visible: true },
          { id: 13, note: 2, visible: true },
          { id: 14, note: 12, visible: true },
          { id: 15, note: 0, visible: true },
          { id: 16, note: 1, visible: true },
        ],
      },
    ],
  },
}

const LEVELS = [
  {
    id: 0,
    level: '10ª Classe',
  },
  {
    id: 1,
    level: '11ª Classe',
  },
  {
    id: 2,
    level: '12ª Classe',
  },
]

export { STUDENT, LEVELS }
